[project]
name = "optimize"
version = "0.1.0"
description = "A research project."

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[tool.setuptools.packages.find]
include = ["optimize"]